Fix: Failed log rollover due to incorrect backup count type
The backup count is of type str after it is read from configuration
file. However, the logging API expects an int for backup count. This
leads to the following error during log rollover.

    --- Logging error ---
    Traceback (most recent call last):
      File "/usr/lib/python3.4/logging/handlers.py", line 72, in emit
        self.doRollover()
      File "/usr/lib/python3.4/logging/handlers.py", line 394, in doRollover
        if self.backupCount > 0:
    TypeError: unorderable types: str() > int()
    Call stack:
      File "./tophn.py", line 427, in <module>
        _main(config)
      File "./tophn.py", line 402, in _main
        archive_list = _check_new_top_story(config)
      File "./tophn.py", line 236, in _check_new_top_story
        logger.info('Top ID on HN: {}'.format(top_id_on_hn))
    Message: 'Top ID on HN: 15426209'
    Arguments: ()

Fix this issue by converting the backup count to int before passing it
to the logging API.